### ISSUE TITLE
Tag compatibility with tactician 1.0

### ISSUE THREAD

**Issue by guiwoda** [madewithlove/tactician-laravel#4]
Hi!
Is there anything I can help to get this project to release a version compatible with tactician 1.0?

Right now I see tests passing with 1.0 and only thing that doesn't look covered is Traits and config.

Thanks!

**Comment by bramdevries** [comment]
I will tag a 1.0.0 release later tonight (it's not different from the current version except that it would depend on tactician 1.0.0)

**Comment by bramdevries** [comment]
Done https://github.com/madewithlove/tactician-laravel/releases/tag/1.0.0
